version: '3'

services:

  # api test
  test:
    container_name: api-test
    image: alesr/restfulgopher-api_test
    build:
      context: .
      dockerfile: resources/api/test/Dockerfile

  # api production
  api:
    container_name: api
    image: alesr/restfulgopher-api
    build:
      context: .
      dockerfile: resources/api/prod/Dockerfile

  # stub api server
  stub_api:
    container_name: stub
    image: alesr/restfulgopher-stub_api
    build:
      context: .
      dockerfile: resources/stub/Dockerfile

  # api spec
  spec:
    container_name: spec
    image: alesr/restfulgopher-api-spec
    build:
      context: .
      dockerfile: resources/spec/Dockerfile

  # swagger editor
  editor:
    container_name: editor
    image: swaggerapi/swagger-editor
    ports:
      - "8080:8080"

  # reverse proxy
  nginx:
    container_name: nginx
    image: alesr/restfulgopher-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - api:api
      - stub_api:stub_api
      - spec:spec
    depends_on:
      - api
      - stub_api
      - spec
    build:
      context: .
      dockerfile: resources/nginx/Dockerfile
